---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

A still-in-progress example

```{r flows-in-map, eval=FALSE}
library("ROracle")
library("tidyverse")
library("sf")

f <- retrieve_airport_flows("2017-01-01", "2017-01-02")
# filter circular flight out
f <- f %>% filter(ADEP != ADES)
f <- f %>% mutate(NB_OF_FLIGHT = as.integer(NB_OF_FLIGHT))
f <- f %>% rename(n = NB_OF_FLIGHT)

# count total yearly flights
f <- f %>% group_by(ADEP) %>% mutate(total = sum(n)) %>% ungroup()


# airport info
ap <- retrieve_airports(c("a"), "2017-01-01", "2017-01-02")
ap <- ap %>% filter(!is.na(LONGITUDE), !is.na(LATITUDE)) %>% st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326)
```

```{r map, eval=FALSE}
## Simutate
# install.packages('gtools')
library(gtools)
library(ggmap)
library(ggrepel)
library(rnaturalearth)
library(sp)
library(rgeos)


airports <- tribble(
  ~icao,  ~longitude, ~latitude,
  "EHAM",  4.764167,  52.30806,
  "EGLL", -0.4613889, 51.4775,
  "LEBL",   2.078333, 41.29694
  )

set.seed(1967)

pairs <- permutations(n = 3,r = 2,v = airports[["icao"]]) %>%
  as_tibble() %>% 
  rename(adep = V1, ades = V2) %>% 
  mutate(n = as.integer(runif(nrow(.), 1, 100)))

#g <- graph_from_data_frame(pairs, directed = TRUE, vertices = airports)

pairs <- merge(pairs, airports, by.x="adep", by.y="icao")
pairs <- merge(pairs, airports, by.x="ades", by.y="icao")




world <- rnaturalearth::countries110
europe <- world[world$region_un == "Europe" & world$name != 'Russia',]

# Let's add a unique ID column to our data.
{{europe@data$id <- row.names(europe@data)}}

# A bounding box for continental Europe.
europe.bbox <- SpatialPolygons(
  list(
    Polygons(
      list(
        Polygon(
          matrix(
            c(
              -25, 29,
              45, 29,
              45,75,
              -25,75,
              -25,29),
            byrow = T,
            ncol = 2)
          )
        ), ID = 1)
    ),
  proj4string = CRS(proj4string(europe)))

# Get polygons that are only in continental Europe.
europe.clipped <-
  {{rgeos::gIntersection(europe, europe.bbox, byid = TRUE, id = europe$id)}}

# tidy up the data for ggplot2
europe.tidy <- broom::tidy(europe.clipped)

#europe.tidy <- dplyr::left_join(europe.tidy, europe@data, by ='id')
gg <- ggplot(europe.tidy, aes(long, lat, group = group)) +
  geom_polygon(alpha = 0.3, color = 'black') +
  # coord_map("azequalarea") +
  hrbrthemes::theme_ipsum_rc() +
  labs(x=NULL, y=NULL, 
    title='Europe',
    caption='Source: http://www.naturalearthdata.com/')


apt <- airports %>% st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

windowsFonts(Times = windowsFont("TT Times New Roman"))
gg + 
  geom_sf(data = apt, inherit.aes = FALSE) +
  theme_set(theme_bw(base_size=12, base_family = 'Times New Roman'))
```

